name: Deploy to CapRover

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
# push:
#   paths:
#     - "apps/jameela/**"
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed

jobs:
  caprover-deploy:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./apps/jameela/Dockerfile
          push: true
          tags: user/app:latest

      - name: CapRover Deploy
        uses: floms/action-caprover@v1
        with:
          host: "${{ secrets.CAPROVER_URL }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          app: jameela
          image: ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
