name: Deploy to CapRover

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
# push:
#   paths:
#     - "apps/jameela/**"
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed

jobs:
  caprover-deploy:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Build Docker Image
        uses: VaultVulp/gp-docker-action@1.1.12
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
            image-name: jameela # Provide Docker image name
            build-context: . 
            dockerfile: ./apps/jameela/Dockerfile

      - name: CapRover Deploy
        uses: floms/action-caprover@v1
        with:
          host: "${{ secrets.CAPROVER_URL }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          app: jameela
          image: ghcr.io/${{ github.repository_owner }}/jameela
